skladiste-env/skladiste/artikli/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views
from .views import PreuzmiStanjeView

app_name = "artikli"

urlpatterns = [
    path("", views.index, name="index"),
    path("admin/", admin.site.urls),
    path("<int:artikl_id>/", views.artikl, name="artikl"),
    path("stanje/", views.prikaz_stanja, name="prikaz_stanja"),
    path("unos_stanja/", views.unos_stanja, name="unos_stanja"),
    path("stanje/preuzmi/", views.preuzmi_stanje, name="preuzmi_stanje"),
]

skladiste-env/skladiste/skladiste/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('artikli/', include('artikli.urls')),
]

skladiste-env/skladiste/artikli/models.py
from django.db import models
from datetime import datetime


class Artikl(models.Model):
    naziv_artikla = models.CharField("naziv artikla", max_length=30)
    opis_artikla = models.CharField("opis artikla", max_length=30)

    def __str__(self):
        return self.naziv_artikla


class JedinicaMjere(models.Model):
    naziv_mjere = models.CharField("naziv mjere", max_length=25)
    oznaka = models.CharField("oznaka", max_length=5)

    def __str__(self):
        return self.naziv_mjere


class Lokacija(models.Model):
    naziv_lokacije = models.CharField("naziv lokacije", max_length=5)
    opis_lokacije = models.CharField("opis lokacije", max_length=100)

    def __str__(self):
        return self.naziv_lokacije


class Stanje(models.Model):
    artikl_id = models.ForeignKey(Artikl, on_delete=models.CASCADE)
    lokacija_id = models.ForeignKey(Lokacija, on_delete=models.CASCADE)
    jedinica_mjere_id = models.ForeignKey(JedinicaMjere, on_delete=models.CASCADE)
    kolicina = models.IntegerField(null=True)
    datum = models.DateTimeField(default=datetime.now)

skladiste-env/skladiste/artikli/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Artikl, Stanje, Lokacija, JedinicaMjere
import openpyxl, barcode
from django.http import HttpResponse
from barcode.writer import ImageWriter
from docx import Document
from docx.shared import Cm, Inches
from PIL import Image
import os


def index(request):
    lista_artikala = Artikl.objects.order_by("naziv_artikla")[:5]
    context = {
        "lista_artikala": lista_artikala,
    }
    return render(request, "artikli/index.html", context)


def artikl(request, artikl_id):
    artikl = get_object_or_404(Artikl, pk=artikl_id)
    context = {
        "artikl": artikl,
    }
    return render(request, "artikli/artikl.html", context)


def prikaz_stanja(request):
    stavke = Stanje.objects.all()
    context = {"stavke": stavke}
    return render(request, "artikli/stanje.html", context)


def unos_stanja(request):
    if request.method == "POST":
        artikl_id = request.POST.get("artikl_id")
        lokacija_id = request.POST.get("lokacija_id")
        jedinica_mjere_id = request.POST.get("jedinica_mjere_id")
        kolicina = request.POST.get("kolicina")
        datum = request.POST.get("datum")

        artikl = get_object_or_404(Artikl, id=artikl_id)
        lokacija = get_object_or_404(Lokacija, id=lokacija_id)
        jedinica_mjere = get_object_or_404(JedinicaMjere, id=jedinica_mjere_id)

        stanje = Stanje.objects.create(
            artikl_id=artikl,
            lokacija_id=lokacija,
            jedinica_mjere_id=jedinica_mjere,
            kolicina=kolicina,
            datum=datum,
        )

        return redirect("artikli:prikaz_stanja")

    artikli = Artikl.objects.all()
    lokacije = Lokacija.objects.all()
    jedinice_mjere = JedinicaMjere.objects.all()

    context = {
        "artikli": artikli,
        "lokacije": lokacije,
        "jedinice_mjere": jedinice_mjere,
    }
    return render(request, "artikli/unos_stanja.html", context)


def preuzmi_stanje(request):
    stanja = Stanje.objects.all()
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.append(["Artikl", "Lokacija", "Jedinica mjere", "Količina", "Datum"])

    for stanje in stanja:
        datum = timezone.localtime(stanje.datum).replace(tzinfo=None)
        ws.append(
            [
                stanje.artikl_id.naziv_artikla,
                stanje.lokacija_id.naziv_lokacije,
                stanje.jedinica_mjere_id.naziv_mjere,
                stanje.kolicina,
                datum,
            ]
        )

    response = HttpResponse(content_type="application/ms-excel")
    response["Content-Disposition"] = 'attachment; filename="stanje.xlsx"'

    wb.save(response)

    return response

skladiste-env/skladiste/artikli/templates/artikli/artikl.html
<h1>{{ artikl.naziv_artikla }}</h1>
<p>{{ artikl.opis_artikla }}</p>
<p>Artikl ID: {{ artikl.id }}</p>

skladiste-env/skladiste/artikli/templates/artikli/index.html
{% if lista_artikala %}
<ul>
  {% for artikl in lista_artikala %}
  <li><a href="/artikli/{{ artikl.id }}/">{{ artikl.naziv_artikla }}</a></li>
  {% endfor %}
</ul>
{% else %}
<p>Nema artikala.</p>
{% endif %}

skladiste-env/skladiste/artikli/templates/artikli/stanje.html
<h1>Stanje skladišta</h1>
<table border="1">
  <thead>
    <tr>
      <th>Artikl</th>
      <th>Lokacija</th>
      <th>Jedinica mjere</th>
      <th>Količina</th>
      <th>Datum</th>
    </tr>
  </thead>
  <tbody>
    {% for stavka in stavke %}
    <tr>
      <td>{{ stavka.artikl_id.naziv_artikla }}</td>
      <td>{{ stavka.lokacija_id.naziv_lokacije }}</td>
      <td>{{ stavka.jedinica_mjere_id.naziv_mjere }}</td>
      <td>{{ stavka.kolicina }}</td>
      <td>{{ stavka.datum }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<a href="{% url 'artikli:preuzmi_stanje' %}" class="btn btn-primary"
  >Preuzmi stanje</a
>

skladiste-env/skladiste/artikli/templates/artikli/unos_stanja.html
<h1>Unos novog stanja skladišta</h1>
<form method="POST">
  {% csrf_token %}
  <div>
    <label for="artikl_id">Artikl:</label>
    <select id="artikl_id" name="artikl_id">
      {% for artikl in artikli %}
      <option value="{{ artikl.id }}">{{ artikl.naziv_artikla }}</option>
      {% endfor %}
    </select>
  </div>
  <div>
    <label for="lokacija_id">Lokacija:</label>
    <select style="width: 10%" id="lokacija_id" name="lokacija_id">
      {% for lokacija in lokacije %}
      <option value="{{ lokacija.id }}">{{ lokacija.naziv }}</option>
      {% endfor %}
    </select>
  </div>
  <div>
    <label for="jedinica_mjere_id">Jedinica mjere:</label>
    <select id="jedinica_mjere_id" name="jedinica_mjere_id">
      {% for jedinica_mjere in jedinice_mjere %}
      <option value="{{ jedinica_mjere.id }}">
        {{ jedinica_mjere.naziv_mjere }}
      </option>
      {% endfor %}
    </select>
  </div>
  <div>
    <label for="kolicina">Količina:</label>
    <input type="number" id="kolicina" name="kolicina" required min="0" />
  </div>
  <div>
    <label for="datum">Datum:</label>
    <input type="date" id="datum" name="datum" required placeholder="{{ {% now
    "m-d-Y" %} }} " />
  </div>
  <button type="submit">Spremi</button>
</form>